### PR TITLE
Added option to manage NS and SOA records (whitelabling)

### LINKED ISSUE #18: Whitelabel reusable delegation issues
I've just installed and configured the AWSR53 plesk extension and have configured whitelabel reusable delegation sets as per AWS instructions, but I'm having an issue whereby even though the whitelabel DNS records are added in the DNS Template within Plesk etc but when the DNS zones are pushed to AWS the whitelabel NS records are replaced with AWS ones resulting in a mismatch + the SOA being incorrect.

The AWS Reusable Delegation Sets section in the Plesk plugin also shows the AWS branded nameservers rather than whitelabel.

Using the latest available version in the Plesk extensions store (2.3-0)

Any ideas?

**AWS R53 web interface:**
2017-07-31 16_56_45-route 53 management console - opera

**Plesk DNS template (also shows up correctly in the individual domain DNS management sections)**
2017-07-31 16_56_28-plesk onyx 17 5 3 - opera

**AWS R53 Plesk Extension**
2017-07-31 16_56_15-amazon route 53 - plesk onyx 17 5 3 - opera

### LINKED ISSUE #30: (Feature) (White Label DNS) Ability to change default SOA and NS records
We are using this extension to manage a server with Route53 DNS, and we configured the route 53 as a white label dns, so instead of using `ns-XXX.awsdns-XX.net`, I want to use `ns1.mydomain.com`.

The problem is that even I changing the default nameservers on plesk settings, it's using the reusable delegation set's nameservers when I create new domains, and simply don't respect the NS entries that I put on the domain DNS Zone settings. 

Apparently the problem is on this two commented lines:

https://github.com/plesk/ext-route53/blob/3c8a5050a261574b5d1b6faacfc4cbf27dbc30c4/src/plib/scripts/route53.php#L24-L37

That are preventing the SOA records being used.

# My suggestion

IMO, the extension should have a setting that allow renaming the Reusable Delegation Set nameservers, and use that Nameservers to configure the domains.

### PR DESCRIPTION
**Pull request by semmasu**
Added an option to manage NS and SOA records with plesk (disabled by default).
Resolves #30 and fixes #18

Before: 
 - Pleask Ignores SOA and NS records when syncing to Route53

After:
 - NS records are synced according to visibility in Plesk panel
 - SOA records are synced according to SOA settings in plesk

### CODE REVIEW

**Comment by toshidex** [comment]
Hi,

how can I compile this extension to be able to use it on the plesk? I need the feature you entered for editing NS and SOA.

**Comment by joostvb** [comment]
> Hi,
> 
> how can I compile this extension to be able to use it on the plesk? I need the feature you entered for editing NS and SOA.

I would like to know this as well.

**Comment by semmasu** [comment]
There is no need to recompile / encrypt the files, just replace the files on your disk with the sourcefiles.
Consider that regarding #41 pre-existing DNS-Zones will not be recreated using the delegationset and therefore setting NS and SOA records to your values will break your DNS-records

**Comment by Nitrocad** [comment]
Hi @semmasu and  @ktak-007!
Can i ask, when will be this request merged into master, and upgradable from plesk panel? 
I'm a hosting provider too using Route53, and it's very annoying to always patch manually.

Thanks a lot! ;)

**Comment by semmasu** [comment]
Hi @Nitrocad 
Sorry, i would also like to have it merged, but i have no permissions on this repo, so i can not do it myself (Thats OK, someone of there team should review it). As it was not merged for almost a year i added @ktak-007 as a reviewer, but no idea if he is the correct person to address. As they have no documentation what way they want Pull-Requests to be done it is just a guess. Probably @MaximSavrilov can help here, but this is also just another guess.

**Comment by Nitrocad** [comment]
Hi @semmasu!

Thanks for your reply, i asked it from the team in the plesk facebook forum.

We will figure it out! :)

**Comment by ayamshanov** [comment]
Hi semmasu,

Thank you for the pull request. We have already reviewed it and looks like everything is ok, and I think the feature will be available in the next Route53 extension release (2.8.0).

**Comment by Nitrocad** [comment]
Thanks you all Plesk Team, it's a wonderful news!!!! :) You are awesome!

**Comment by Nitrocad** [comment]
Hurray!
Thanks a lot! Can i ask when can we update it from the ext. catalog?

**Comment by iget-master** [comment]
@ktak-007 can you explain from where the SOA record nameserver come from? Changing the "primary name server" on options don't work for me, it always get the ns4 for me.

**Comment by ayamshanov** [comment]
Hi @iget-master,
If I am not mistaken, it comes from https://github.com/plesk/ext-route53/blob/master/src/plib/scripts/route53.php#L192-L204.

**Comment by iget-master** [comment]
So it's always the first nameserver in the array (not necessarily the
primary, in my case it's being always the ns4)

Em sex., 14 de mai. de 2021 01:10, Alexander Yamshanov <
***@***.***> escreveu:

**Pull request merged**
